### ISSUE TITLE
Dudas sobre el funcionamiento

### ISSUE THREAD

**Issue by manuman94** [duhow/CodeIgniter-Advanced-Models#1]
Buenos días, 

He estado echándole un vistazo a los modelos y parecen bastante completos. Ya que el readme no explica cómo funcionan, ¿podrías indicar qué se puede hacer con cada uno de los modelos y un ejemplo de su llamada en un controlador? Sería muy útil.

Me interesan sobre todo el de Prestashop, que imagino que lo habrás usado para crear una API para hacer una aplicación móvil o similar; el de Redsys, que imagino que se utilizará para procesar pagos en una web app con CodeIgniter y el de Passbook, que sinceramente no tengo ni idea de cómo funciona a nivel técnico (sólo lo utilizo para comprar entradas de vez en cuando).

Muchas gracias, un saludo.

**Comment by duhow** [comment]
Son funciones que desarrollé en su momento, puedes hacer una lista de las "funciones" que hay y ver el uso que tienen... 🤣 No están todas todas las funciones, sólo algunas que he necesitado hacer.
Passbook está a medio implementar, falta el tema de la licencia de Apple.

**Comment by manuman94** [comment]
Sí! He estado revisando las clases y están muy completas. Te felicito 👍 

El modelo de Prestashop está muy completo, prácticamente cubre las necesidades. Eres un crack!

Un saludo.
